### PR TITLE
Fix 0.5 depwarn and other problems

### LINKED ISSUE #22: Dependence on Zlib is causing precompile issues
Hi,

It appears that Zlib is semi-deprecated in favor of Libz.jl. In any case, precompilation is failing on Zlib causing cascading Travis errors (this affects GeoIP.jl, for example).

### PR DESCRIPTION
**Pull request by yuyichao**
Requires https://github.com/JuliaLang/Compat.jl/pull/201 and a new tag of Compat.jl . **DO NOT MERGE YET!!!**

* Fix 0.5 depwarn for string types, `readstring`, and `unsafe_write`
* Fix test to support loading package in `LOAD_PATH`
* Enable pre-compilation. Fix #22

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -137,5 +137,5 @@ close(dir)
 
 
 if !Debug
-	run(`rm -rf $tmp`)
+    run(`rm -rf $tmp`)
```
Comment (tkelman) [inline test/runtests.jl]: use the julia `rm` function, or `mktempdir() do tmp` around the whole thing?

Comment (yuyichao) [inline test/runtests.jl]: Given that there's a debug option to disable this, I'll just switch to `rm` function.

File: src/ZipFile.jl [hunk 2]
```diff
@@ -497,13 +499,13 @@ function position(f::ReadableFile)
 end
 
 # Write nb elements located at p into f.
-function write(f::WritableFile, p::Ptr, nb::Integer)
+function unsafe_write(f::WritableFile, p::Ptr, nb::Integer)
```
Comment (vtjnash) [inline src/ZipFile.jl]: wrong signature to override – see documentation

File: src/iojunk.jl [hunk 3]
```diff
@@ -3,7 +3,7 @@ function write{T}(w::WritableFile, a::Array{T})
 	# If this is not provided, Base.IO write methods will write
```
Comment (vtjnash) [inline src/iojunk.jl]: the corresponding method in base should be more efficient than these now (due to dispatching to `unsafe_write` more uniformly)

File: src/ZipFile.jl (hunk 2 above)
Comment (vtjnash) [inline src/ZipFile.jl]: also, what's up with `b = reinterpret(UInt8, reshape(a, length(a)))`, it looks like a complicated no-op?

File: src/iojunk.jl [hunk 4]
```diff
@@ -51,7 +51,7 @@ end
 
 # Read and return a byte from f. Throws EOFError if there is no more byte to read.
 function read(f::ReadableFile, ::Type{UInt8})
-	# This function needs to be fast because readbytes, readall, etc.
+	# This function needs to be fast because readbytes, readstring, etc.
```
Comment (vtjnash) [inline src/iojunk.jl]: could re-write this to use a `Ref{UInt8}` object now. see usages in Base, for instance.

Comment (yuyichao) [inline src/iojunk.jl]: FWIW, this package is still claiming 0.3 support, which is why I don't want to change it too much..... Maybe it's fine to drop 0.3 support? @fhs

**Comment by fhs** [comment]
@yuyichao Yes, it's ok to drop support for 0.3.

Also, please remove indentation changes from runtests.jl. We use tabs for indentation instead of spaces.

**Comment by yuyichao** [comment]
> Also, please remove indentation changes from runtests.jl. We use tabs for indentation instead of spaces.

I changed it because it was a mix. I can change it back....

**Comment by yuyichao** [comment]
All of @vtjnash 's comment should be addressed (maybe except the `read` since the interface `unsafe_read` is not already implemented). 0.3 should still be supported and at last it passed tests on juliabox.... Indentation should be all reverted (including the inconsistent ones....)

Still relies on a new Compat tag so **DON'T MERGE YET**

**Comment by vtjnash** [comment]
lgtm

**Comment by yuyichao** [comment]
Compat.jl tagged and this should be good to go. The CI failure on master seems to be a Zip.jl issue.

**Comment by yuyichao** [comment]
ping

**Comment by fhs** [comment]
Anyone look into the issue with Zlib.jl?

It it going to be fixed or we need to move to [Libz.jl](https://github.com/BioJulia/Libz.jl)? Last time I checked, Libz.jl doesn't have all the functionality we need.

**Comment by bjarthur** [comment]
meow

**Comment by fhs** [comment]
Can you rebase and make the tests pass?

**Comment by yuyichao** [comment]
Pass test for me locally on 0.3 to master. I can't say that I like this approach but it should be reasonably well defined and complete....

**Comment by fhs** [comment]
You can actually drop support for julia 0.3.

I wanted to get the tests working before moving to Libz.jl. Last time I looked at Libz.jl, it didn't have everything we needed. PR welcome to support Libz.jl.

**Comment by fhs** [comment]
ok to merge now?

**Comment by yuyichao** [comment]
> You can actually drop support for julia 0.3.

At least the test pass for now.

> I wanted to get the tests working before moving to Libz.jl. Last time I looked at Libz.jl, it didn't have everything we needed. PR welcome to support Libz.jl.

And the comment I add is to make it clear that you can remove that code when you move to Libz.

> ok to merge now?

Yes (you already did...)
